#spring.application.name=spring-cloud-eureka
#
#server.port=8000
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8000/eureka/

##定义服务名称
spring:
  application:
    name: spring-cloud-eureka
###服务端口号
sevice:
  port: 8000
eureka:
  instance:
    ###注册中心ip地址
    hostname: localhost
  client:
    ####因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候是需要是为true）
    register-with-eureka: false
    ###因为自己是注册中心，不需要去检索服务信息
    fetch-registry: false
    serviceUrl:
      ##注册地址
      defaultZone: http://${eureka.instance.hostname}:${sevice.port}/eureka/