#spring.application.name=spring-cloud-eureka
#
#server.port=8000
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8000/eureka/

##定义服务名称
spring:
  application:
    name: spring-cloud-eureka
#  security:
#    user:
#      name: root
#      password: 123456
###服务端口号
sevice:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${sevice.port}/eureka/
