spring:
  application:
    name: pay-app
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000