server:
  port: 8888
spring:
  application:
    name: rig-app
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-detail: always


zuul:
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  #default is SEMAPHORE
  ribbonIsolationStrategy: THREAD
  routes:
    pay:
      path: /pay/**
      serviceId: pay-app
#zuul:
#  TestFilter:
#    pre:
#      disable: true