server:
  port: 8888
spring:
  application:
    name: rig-app
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#禁用过滤器
#zuul:
#  TestFilter:
#    pre:
#      disable: true