spring:
  application:
    name: acc-app
server:
  port: 9000
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.5.31:8080/eureka/
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true